name: Golang

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        go:
          - 1.18
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Go Test
        run: make test
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          env_vars: RUNNER_OS,RUNNER_ARCH,GOROOT
