name: Release

on:
  push:
    branches:
      - master

jobs:
  release-please:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: GoogleCloudPlatform/release-please-action@v3
        with:
          release-type: go
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          pull-request-title-pattern: "release: ${version}"
